// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc20.PrototypingBoard.subsystems;

import org.usfirst.frc20.PrototypingBoard.RobotMap;
import org.usfirst.frc20.PrototypingBoard.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc20.PrototypingBoard.Robot;

/**
 *
 */
public class Board extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    Victor victor = RobotMap.boardVictor;
    Jaguar jaguar = RobotMap.boardJaguar;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Talon talon = RobotMap.boardTalon;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new RunAllMotors());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    public void runAllMotors(Joystick stick) {
        victor.set(stick.getRawAxis(2));
        jaguar.set(stick.getRawAxis(2));
        talon.set(stick.getRawAxis(2));
        Robot.logger.logValue("All Motors Speed", stick.getRawAxis(2));
    }

    public void runTalon(Joystick stick) {
        talon.set(stick.getRawAxis(2));
        Robot.logger.logValue("Talon Speed", stick.getRawAxis(2));
    }

    public void runJaguar(Joystick stick) {
        jaguar.set(stick.getRawAxis(2));
        Robot.logger.logValue("Jaguar Speed", stick.getRawAxis(2));
    }

    public void runVictor(Joystick stick) {
        victor.set(stick.getRawAxis(2));
        Robot.logger.logValue("Victor Speed", stick.getRawAxis(2));
    }
}
