// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc20.SensorBoard.commands;

import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import java.util.TimerTask;
import org.usfirst.frc20.SensorBoard.RobotMap;

/**
 *
 */
public class  Turn180 extends Command {
    Gyro gyro;
    RobotMap driveTrainObjects;//the mapping object so we can mess with the 
    Jaguar topRight, topLeft, bottomLeft, bottomRight;
    double speed = .25;
    boolean turned = false;
    public Turn180() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        //all these intiations are from the RobotMap class
        driveTrainObjects = new RobotMap();
        gyro = driveTrainObjects.getGyro();
        topRight = driveTrainObjects.getTopRightJag();
        topLeft = driveTrainObjects.getTopLeftJag();
        bottomRight = driveTrainObjects.getBottomRightJag();
        bottomLeft = driveTrainObjects.getBottomLeftJag();
    }
    //sets the speed at which the robot turns very important
    public void setSpeed(double speed){
        this.speed = speed;
    }
    TimerTask checkForAngle = new TimerTask(){
        public void run() {
            double angle = Math.PI;
            if(angle <= gyro.getAngle()){
            topLeft.set(0);
            bottomLeft.set(0);
            topRight.set(0);
            bottomRight.set(0);
            turned = true;
            }
        }
    };
    /* first it resets the gyro angle
     * starts the jag motors in reverse from each side at the specified speed
     * speed's default is 25% power
     * starts the timertask and exceutes it every 100 milisec.
     * once it has reached 180, the motors stop 
     */
    protected void execute() {
            gyro.reset();
            topLeft.set(speed);
            bottomLeft.set(speed);
            topRight.set(-speed);
            bottomRight.set(-speed);
            while(true){
                if(turned){
            try {
                checkForAngle.wait(100);
                //TODO this exception might actually hurt us
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
                }else {
                    break;
                }
            }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return turned;
    }

    // Called once after isFinished returns true
    protected void end() {
        //TODO delete this code below
        System.out.println("Hurray!"); 
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
