// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc20.SensorBoard.commands;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.PIDCommand;
import org.usfirst.frc20.SensorBoard.Robot;
import org.usfirst.frc20.SensorBoard.RobotMap;
import org.usfirst.frc20.SensorBoard.subsystems.PIDmag;
import org.usfirst.frc20.SensorBoard.OI;
/**
 *
 */
public class  Up extends PIDCommand {
    PIDmag x=new PIDmag();
    OI y = new OI();
    int setpoint = 0;
    Joystick joy = y.xbox;
    boolean but1 = false;
    public Up() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("Up", 1.0, 0.0, 0.0, 0.05);
        
        getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(0.2);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
	
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pIDmag);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
		
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return RobotMap.pIDmagMagneticEncoder.pidGet();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
		
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        RobotMap.pIDmagJag.pidWrite(output);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
         if (but1 != joy.getRawButton(5)) {
                if (joy.getRawButton(5)) {
                    x.setSetpoint(setpoint+0.1);
                }
                but1 = joy.getRawButton(1);
            }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
