// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc20.Robot.subsystems;

import org.usfirst.frc20.Robot.RobotMap;
import org.usfirst.frc20.Robot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Collector extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController beltMotor = RobotMap.collectorbeltMotor;
    SpeedController rollerMotor = RobotMap.collectorrollerMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private final double rollerMotorUpSpeed = 1.0;
    private final double rollerMotorDownSpeed = -1.0;
    private final double rollerMotorOffSpeed = 0.0;
    private final double beltMotorUpSpeed = 1.0;
    private final double beltMotorIdleSpeed = 0.5;
    private final double beltMotorDownSpeed = -1.0;
    private final double beltMotorOffSpeed = 0.0;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    //drives the roller upward and the belt
    public void driveUp(){
        rollerMotor.set(rollerMotorUpSpeed);
        beltMotor.set(beltMotorUpSpeed);
    }
    //drives the collector motors in reverse, belt too
    public void driveDown(){
        rollerMotor.set(rollerMotorDownSpeed);
        beltMotor.set(rollerMotorDownSpeed);
    }
    
    public void idle(){
        rollerMotor.set(rollerMotorOffSpeed);
        beltMotor.set(beltMotorIdleSpeed);
    }
    
    public void off(){
        rollerMotor.set(rollerMotorOffSpeed);
        beltMotor.set(beltMotorOffSpeed);
    }
}