// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc20.Robot.subsystems;
import org.usfirst.frc20.Robot.RobotMap;
import org.usfirst.frc20.Robot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Collector extends Subsystem {

    SpeedController beltMotor = RobotMap.collectorbeltMotor;
    SpeedController rollerMotor = RobotMap.collectorrollerMotor;

    private final double kRollerUpSpeed = 1.0;
    private final double kRollerDownSpeed = -1.0;
    private final double kRollerOffSpeed = 0.0;
    private final double kBeltUpSpeed = 1.0;
    private final double kBeltIdleSpeed = 0.5;
    private final double kBeltDownSpeed = -1.0;
    private final double kBeltOffSpeed = 0.0;
    public final double kDiscShootTimeInSeconds = .5;
    public final long kWaitAfterShotTimeInMillis = 500;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        
        setDefaultCommand(new CollectorIdle());
    }
    //drives the roller upward and the belt
    public void driveUp(){
        rollerMotor.set(kRollerUpSpeed);
        beltMotor.set(kBeltUpSpeed);
    }
    //drives the collector motors in reverse, belt too
    public void driveDown(){
        rollerMotor.set(kRollerDownSpeed);
        beltMotor.set(kBeltDownSpeed);
    }
    
    public void idle(){
        rollerMotor.set(kRollerOffSpeed);
        beltMotor.set(kBeltIdleSpeed);
    }
    
    public void off(){
        rollerMotor.set(kRollerOffSpeed);
        beltMotor.set(kBeltOffSpeed);
    }
}