// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.RobotDrive.MotorType;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Jaguar driveTrainRightJag;
    public static Jaguar driveTrainLeftJag;
    public static RobotDrive driveTrainRobotDrive;
    public static Jaguar tiltTiltJag;
    public static Jaguar shooterShooterJag;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightJag = new Jaguar(1, 4);
	LiveWindow.addActuator("DriveTrain", "RightJag", driveTrainRightJag);
        
        driveTrainLeftJag = new Jaguar(1, 2);
	LiveWindow.addActuator("DriveTrain", "LeftJag", driveTrainLeftJag);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftJag, driveTrainRightJag);
	
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        

        tiltTiltJag = new Jaguar(1, 10);
	LiveWindow.addActuator("Tilt", "TiltJag", tiltTiltJag);
        
        shooterShooterJag = new Jaguar(1, 9);
	LiveWindow.addActuator("Shooter", "ShooterJag", shooterShooterJag);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
