// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc20.Robot.subsystems;
import org.usfirst.frc20.Robot.RobotMap;
import org.usfirst.frc20.Robot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Shooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Jaguar topWheelsJag = RobotMap.shootertopWheelsJag;
    Jaguar bottomWheelsJag = RobotMap.shooterbottomWheelsJag;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    private static final double TOPWHEELSSPEEDKEY = 0.25;
    private static final double BOTTOMWHEELSSPEEDKEY = 1.0;
    private static final double TOPWHEELSSPEEDFENDER = 0.15;
    private static final double BOTTOMWHEELSSPEEDFENDER = .75;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ShooterOff());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void stop(){
        topWheelsJag.set(0);
        bottomWheelsJag.set(0);
    }
    
    public void fender(){
        topWheelsJag.set(TOPWHEELSSPEEDFENDER);
        bottomWheelsJag.set(BOTTOMWHEELSSPEEDFENDER);
    }
    
    public void key(){
        topWheelsJag.set(TOPWHEELSSPEEDKEY);
        bottomWheelsJag.set(BOTTOMWHEELSSPEEDKEY);
    }
}
