// RobotBuilder Version: 0.0.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc20.Robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc20.Robot.Robot;
/**
 *
 */
public class  DrivetrainDrive extends Command {
    
    double time;
    double outputMagnitude;
    double curve;
    
    public DrivetrainDrive(double t, double m, double c) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        time = t;
        outputMagnitude = m;
        curve = c;
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        setTimeout(time);
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.drivetrain.drive(outputMagnitude, curve);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
